class Comic {
  final String image;
  final String title;
  final String year;
  final String leftCount;
  final String price;
  final String rare;
  final bool blindBox;
  final String subtitle;
  final String like;
  final String comment;
  final String subtitleDesc;
  final String dropDate;
  final String totalEditions;
  final String remainingEditions;
  final String editionType;
  final String rarity;
  final String listPrice;
  final String license;
  final String brand;
  final String series;
  final String season;

  const Comic({
    required this.image,
    required this.title,
    required this.year,
    required this.leftCount,
    required this.price,
    required this.rare,
    required this.blindBox,
    required this.subtitle,
    required this.like,
    required this.comment,
    required this.subtitleDesc,
    required this.dropDate,
    required this.totalEditions,
    required this.remainingEditions,
    required this.editionType,
    required this.rarity,
    required this.listPrice,
    required this.license,
    required this.brand,
    required this.series,
    required this.season,
  });
}

class ComicsData {
  static const List<Comic> comics = [
    Comic(
      image: "assets/comics_assets/comic.webp",
      title: "Un/Sacred volume #2",
      year: "2020",
      leftCount: "975 left",
      price: "7.98",
      rare: "Rare",
      blindBox: false,
      subtitle: "Main Cover",
      like: "123",
      comment: "45",
      subtitleDesc:
          "Mirka Andolfo's masterpiece continues with stunning artwork and captivating storytelling.",
      dropDate: "2025-07-25",
      totalEditions: "1000",
      remainingEditions: "974",
      editionType: "Limited",
      rarity: "Ultra Rare",
      listPrice: "14.99",
      license: "Marvel",
      brand: "Marvel Comics",
      series: "Un/Sacred",
      season: "2025",
    ),
    Comic(
      image: "assets/comics_assets/comic1.jpeg",
      title: "The BoogyMan #7",
      year: "2017",
      leftCount: "979 left",
      price: "7.98",
      rare: "Common",
      blindBox: false,
      subtitle: "Issue #7",
      like: "50",
      comment: "10",
      subtitleDesc:
          "The terrifying tale of the BoogyMan continues in this spine-chilling issue.",
      dropDate: "2023-06-15",
      totalEditions: "1000",
      remainingEditions: "979",
      editionType: "Standard",
      rarity: "Common",
      listPrice: "7.98",
      license: "DC Comics",
      brand: "DC Comics",
      series: "The BoogyMan",
      season: "2023",
    ),
    Comic(
      image: "assets/comics_assets/comic2.webp",
      title: "Un/Sacred Mirka Andolfo Main Cover",
      year: "2025",
      leftCount: "974 left",
      price: "7.98",
      rare: "Rare",
      blindBox: false,
      subtitle: "Main Cover",
      like: "150",
      comment: "30",
      subtitleDesc:
          "Exclusive main cover edition featuring Mirka Andolfo's incredible artwork.",
      dropDate: "2025-07-25",
      totalEditions: "1000",
      remainingEditions: "974",
      editionType: "Limited",
      rarity: "Ultra Rare",
      listPrice: "14.99",
      license: "Marvel",
      brand: "Marvel Comics",
      series: "Un/Sacred",
      season: "2025",
    ),
    Comic(
      image: "assets/comics_assets/comic3.jpeg",
      title: "X-Men Marvel Comics Group Cover",
      year: "2018",
      leftCount: "975 left",
      price: "7.98",
      rare: "Common",
      blindBox: false,
      subtitle: "Group Cover",
      like: "70",
      comment: "15",
      subtitleDesc:
          "Classic X-Men team cover featuring all your favorite mutant heroes.",
      dropDate: "2024-03-10",
      totalEditions: "1000",
      remainingEditions: "975",
      editionType: "Standard",
      rarity: "Common",
      listPrice: "7.98",
      license: "Marvel",
      brand: "Marvel Comics",
      series: "X-Men",
      season: "2024",
    ),
    Comic(
      image: "assets/comics_assets/comic4.webp",
      title: "The BoogyMan #7",
      year: "2025",
      leftCount: "979 left",
      price: "7.98",
      rare: "Rare",
      blindBox: false,
      subtitle: "Issue #7",
      like: "200",
      comment: "50",
      subtitleDesc:
          "Another terrifying chapter in the BoogyMan saga with enhanced artwork.",
      dropDate: "2025-07-25",
      totalEditions: "1000",
      remainingEditions: "979",
      editionType: "Limited",
      rarity: "Ultra Rare",
      listPrice: "14.99",
      license: "DC Comics",
      brand: "DC Comics",
      series: "The BoogyMan",
      season: "2025",
    ),
    Comic(
      image: "assets/comics_assets/comic5.webp",
      title: "Sherlock Holmes: Year One #4",
      year: "2011",
      leftCount: "979 left",
      price: "7.98",
      rare: "Common",
      blindBox: false,
      subtitle: "Issue #4",
      like: "100",
      comment: "20",
      subtitleDesc:
          "The early years of the world's greatest detective in Victorian London.",
      dropDate: "2024-10-01",
      totalEditions: "1000",
      remainingEditions: "979",
      editionType: "Standard",
      rarity: "Common",
      listPrice: "7.98",
      license: "DC Comics",
      brand: "DC Comics",
      series: "Sherlock Holmes",
      season: "2024",
    ),
    Comic(
      image: "assets/comics_assets/comic6.jpeg",
      title: "Army of Darkness: Shop Til You Drop Dead #3",
      year: "2004",
      leftCount: "979 left",
      price: "7.98",
      rare: "Common",
      blindBox: false,
      subtitle: "Issue #3",
      like: "80",
      comment: "15",
      subtitleDesc:
          "Ash Williams faces the deadites in a shopping mall showdown.",
      dropDate: "2025-05-15",
      totalEditions: "1000",
      remainingEditions: "979",
      editionType: "Standard",
      rarity: "Common",
      listPrice: "7.98",
      license: "Dark Horse Comics",
      brand: "Dark Horse Comics",
      series: "Army of Darkness",
      season: "2025",
    ),
    Comic(
      image: "assets/comics_assets/comic7.jpeg",
      title: "PLANET DEATH #1",
      year: "2025",
      leftCount: "1949 left",
      price: "8.98",
      rare: "Rare",
      blindBox: false,
      subtitle: "Issue #1",
      like: "300",
      comment: "70",
      subtitleDesc:
          "A dying planet's last hope lies in the hands of unlikely heroes.",
      dropDate: "2025-07-01",
      totalEditions: "2000",
      remainingEditions: "1949",
      editionType: "Limited",
      rarity: "Ultra Rare",
      listPrice: "14.99",
      license: "Image Comics",
      brand: "Image Comics",
      series: "Planet Death",
      season: "2025",
    ),
    Comic(
      image: "assets/comics_assets/comic8.jpeg",
      title: "Ultraman #4",
      year: "2016",
      leftCount: "1796 left",
      price: "14.99",
      rare: "Rare",
      blindBox: false,
      subtitle: "Issue #4",
      like: "250",
      comment: "60",
      subtitleDesc:
          "The legendary giant hero battles cosmic threats to protect Earth.",
      dropDate: "2024-09-20",
      totalEditions: "1000",
      remainingEditions: "1796",
      editionType: "Limited",
      rarity: "Ultra Rare",
      listPrice: "14.99",
      license: "Shueisha",
      brand: "Shueisha",
      series: "Ultraman",
      season: "2024",
    ),
    Comic(
      image: "assets/comics_assets/comic9.jpeg",
      title: "Uncanny X-Men #17",
      year: "2024",
      leftCount: "967 left",
      price: "7.98",
      rare: "Common",
      blindBox: false,
      subtitle: "Issue #17",
      like: "180",
      comment: "45",
      subtitleDesc:
          "The X-Men face their greatest challenge yet in this action-packed issue.",
      dropDate: "2024-11-10",
      totalEditions: "1000",
      remainingEditions: "967",
      editionType: "Standard",
      rarity: "Common",
      listPrice: "7.98",
      license: "Marvel",
      brand: "Marvel Comics",
      series: "Uncanny X-Men",
      season: "2024",
    ),
    Comic(
      image: "assets/comics_assets/comic10.jpeg",
      title: "Marvel Swimsuit Special: Friends, Foes & Rivals #1",
      year: "2025",
      leftCount: "951 left",
      price: "8.98",
      rare: "Rare",
      blindBox: false,
      subtitle: "Special #1",
      like: "220",
      comment: "55",
      subtitleDesc:
          "Annual swimsuit special featuring Marvel's most popular characters.",
      dropDate: "2025-06-01",
      totalEditions: "1000",
      remainingEditions: "951",
      editionType: "Limited",
      rarity: "Ultra Rare",
      listPrice: "14.99",
      license: "Marvel",
      brand: "Marvel Comics",
      series: "Marvel Swimsuit",
      season: "2025",
    ),
    Comic(
      image: "assets/comics_assets/comic11.jpeg",
      title: "Laura Kinney: Wolverine #8",
      year: "2024",
      leftCount: "980 left",
      price: "6.98",
      rare: "Common",
      blindBox: false,
      subtitle: "Issue #8",
      like: "150",
      comment: "35",
      subtitleDesc:
          "X-23 continues her journey as the new Wolverine with deadly precision.",
      dropDate: "2024-12-15",
      totalEditions: "1000",
      remainingEditions: "980",
      editionType: "Standard",
      rarity: "Common",
      listPrice: "6.98",
      license: "Marvel",
      brand: "Marvel Comics",
      series: "Wolverine",
      season: "2024",
    ),
    Comic(
      image: "assets/comics_assets/comic12.jpeg",
      title: "Magik #7",
      year: "2025",
      leftCount: "977 left",
      price: "6.98",
      rare: "Rare",
      blindBox: false,
      subtitle: "Issue #7",
      like: "200",
      comment: "50",
      subtitleDesc:
          "Illyana Rasputin navigates the mystical realms with her soulsword.",
      dropDate: "2025-07-25",
      totalEditions: "1000",
      remainingEditions: "977",
      editionType: "Limited",
      rarity: "Ultra Rare",
      listPrice: "14.99",
      license: "Marvel",
      brand: "Marvel Comics",
      series: "X-Men",
      season: "2025",
    ),
    Comic(
      image: "assets/comics_assets/comic13.jpeg",
      title: "Fantastic Four: First Steps #1",
      year: "2025",
      leftCount: "949 left",
      price: "7.98",
      rare: "Common",
      blindBox: false,
      subtitle: "Issue #1",
      like: "120",
      comment: "30",
      subtitleDesc:
          "The first family of Marvel begins their incredible journey.",
      dropDate: "2025-08-01",
      totalEditions: "1000",
      remainingEditions: "949",
      editionType: "Standard",
      rarity: "Common",
      listPrice: "7.98",
      license: "Marvel",
      brand: "Marvel Comics",
      series: "Fantastic Four",
      season: "2025",
    ),
  ];
}
